### ISSUE TITLE
Goal: Node Operator docs

### ISSUE THREAD

**Issue by markholdex** [truf-network/docs#3]
# [Specs](https://docs.google.com/document/d/1GuWcC9YdeMINhcTKcqh-0a5hhYUm_MuL75H1-GxGeDM/edit?tab=t.0#heading=h.acexyr3bbunx)

## Problem
- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #21
- [x] #22

ETA: ready tomorrow.

**Comment by markholdex** [comment]
This Goal should be next after 
- #5

**Comment by MicBun** [comment]
Right, will do that 👍

**Comment by markholdex** [comment]
@MicBun what is the ETA for this Goal?

**Comment by MicBun** [comment]
Hi @markholdex, I think I can solve it with one PR here:
https://github.com/truf-network/docs/pull/23

could you check my writings there? thanks

**Comment by MicBun** [comment]
Looks good to me, I will close the goal as complete now
