### ISSUE TITLE
Goal: Developer docs

### ISSUE THREAD

**Issue by markholdex** [truf-network/docs#4]
# [Specs](https://docs.google.com/document/d/1GuWcC9YdeMINhcTKcqh-0a5hhYUm_MuL75H1-GxGeDM/edit?tab=t.0#heading=h.fdma9axlgkke)

## Problem
- [x] #24
- [x] #25
- [x] #26
- [x] #27

**Comment by markholdex** [comment]
This Goal should go next after:
- #5
- #3

**Comment by zolotokrylin** [comment]
@angelicawill are you the one who can trigger the build and deployment, please?

**Comment by MicBun** [comment]
Hi @zolotokrylin, I can trigger the build and deployment. I have triggered it, and the latest update will reflect soon.
