### ISSUE TITLE
Goal: data Consumer docs

### ISSUE THREAD

**Issue by markholdex** [truf-network/docs#5]
# [Specs](https://docs.google.com/document/d/1GuWcC9YdeMINhcTKcqh-0a5hhYUm_MuL75H1-GxGeDM/edit?tab=t.0#heading=h.c4iz7p5uy49n)

# [Live website](https://docs.truf.network/home)

# Problem
- [x] https://github.com/truf-network/docs/issues/6
- [x] https://github.com/truf-network/docs/issues/7
- [x] #11
- [x] #15
- [x] #14
- [x] #13
- [x] #12

**Comment by markholdex** [comment]
@MicBun can you please take on this Goal? Feel free to expand on the specs before proceeding if I missed something. Thanks!

**Comment by MicBun** [comment]
Sure things! 👍

**Comment by MicBun** [comment]
# Problem
- [ ] Problem: Lack of access to TRUF Network's mintlify
- [ ] Problem: Consumer Docs section is missing from Documentation

**Comment by MicBun** [comment]
I think it is good. Will close the Goal now

@markholdex
